version: '3.8'
services:
    trinkspiele:
        container_name: trinkspiele
        build: .
        image: trinkspiele
        restart: unless-stopped
        ports:
            - "5000:5000"
        volumes:
            - .:/app
