version: '3.9'
services:
    trinkspiele:
        container_name: trinkspiele
        build: .
        restart: unless-stopped
        ports:
            - "5000:5000"
        volumes:
            - .:/app
