# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application build test

on:
  push:
    branches: [ main, add-tests ]
  pull_request:
    branches: [ main, add-tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --cov func --cov-branch --cov-report term-missing
